---
title: "Import microbial plate growth absorbance data for salinity growth trials"
author: "Maximilian Berthold, Douglas A. Campbell, Alyson MacCormack"
date: "`r format(Sys.Date())`"
output:
  html_document:
    df_print: paged
    code_folding: hide   

---
This .Rmd imports Clariostar Ab wellplate files.
The size of the wellplate does not matter; the import creates columns for RowColumn LetterNumber (A01 etc.) for the largest plate type in the list of files.
Import of smaller plate types results in NA in the non-existent RowColumn for that plate.


```{r set project variables, echo=FALSE}
Project <- "PGW"


InocVol <- 0.2 #share of inoculation volume
CondVol <- 0.8 #share of condition medium, here salinity

#set variables for file import & processing of Absorbance files
FP1 <- ".."
FP2 <- "RawData"
InstrumentPath <- "CSdata"
FileIDSingle <- "_Ab_"
DataPath <- file.path(paste(FP1, FP2, InstrumentPath, sep = "/"), fsep = .Platform$file.sep)
DataIn <- "ProcessData"
DataOut <- "TidiedData"
DataCalibration <- "CalibrationData"

FileEncodeCS <- "UTF-8" 
DelimCS <- ","

#make this more robust to variable file formats by skipping rows until 'Well' detected; not yet implemented
#https://community.rstudio.com/t/read-csv-file-until/41711/2
HeaderRowsCS <- 6

#increase memory space on local computer, to cope with large dataset
memory.limit(size = 35000)
```


```{r load libraries, echo=FALSE, message = FALSE, warning = FALSE} 
# libraries; Note check actual dependencies
library(tidyverse)
library(lubridate)
library(googledrive)
library(googlesheets4)

```


```{r load local catalog, message = FALSE, warning = FALSE, echo=FALSE}
#deauthorizes access to googlesheet
gs4_deauth()

MetaData <- read_sheet("https://docs.google.com/spreadsheets/d/1QWMLB_0E9uNK0o67pypTZKjkyjEpBMEzoYTi1Db86Q8/edit?usp=sharing")

MediaData <- read_sheet("https://docs.google.com/spreadsheets/d/1E3C0_3ziDp-NnvvI5l7ZgqcanKZxSqgaWxk3uUmgRLA/edit?usp=sharing")

BlankData <- readRDS(file = file.path(paste(FP1, DataIn, sep = "/"), paste(Project, "MediaBlankAll.Rds", sep = "_"), fsep = .Platform$file.sep))

CalibrationCellCount <- readRDS(file = file.path(paste(FP1, DataCalibration, sep = "/"), paste(Project,"Calibration_OD_CellCount.Rds", sep = "_"),fsep = .Platform$file.sep))
CalibrationChloro <- readRDS(file = file.path(paste(FP1, DataCalibration, sep = "/"), paste(Project,"Calibration_OD_Chl.Rds", sep = "_"), fsep = .Platform$file.sep)) 
CalibrationETR <- readRDS(file = file.path(paste(FP1, DataCalibration, sep = "/"), paste(Project,"SolFitCal.Rds", sep = "_"), fsep = .Platform$file.sep))


MediaDataTarget <- MediaData %>% #sloppy way of binding meta-data information with both inoculation and target media
  select(MediaID, MeasuredSalinity_ppt) %>%
  rename("target_media_id" ="MediaID")

MediaDataInoc <- MediaData %>%
  select(MediaID, MeasuredSalinity_ppt) %>%
  rename("inoc_media_id" = "MediaID")  

MetaMediaTarget <- full_join(MetaData, MediaDataTarget) %>%
  rename("TargMedSal" = "MeasuredSalinity_ppt")

MetaMediaInoc <- full_join(MetaData, MediaDataInoc) %>%
  rename("InocMedSal" = "MeasuredSalinity_ppt")

MetaMedia <- full_join(MetaMediaTarget, MetaMediaInoc) %>% #calculate actual salinity within media, besides desired salinity 
  mutate(CalcSal = ((TargMedSal*media_inocul_L)+(InocMedSal*culture_inocul_L))/(media_inocul_L+culture_inocul_L))

MetaMediaBlank <- full_join(MetaMedia, BlankData) 


AbFilesCS <- list.files(path = DataPath, pattern = FileIDSingle, full.names = TRUE) 
unique(duplicated(AbFilesCS))

```



```{r data read adds filename for file import & processing ClarioStar Ab, echo=FALSE}

read.delim_plus <- function(flnm, file_encode, delimiter, header_rows){read.delim(flnm, fileEncoding = file_encode, sep = delimiter,  skip = header_rows, row.names = NULL) %>% mutate(filename = flnm)
}

AbSpecCS <- AbFilesCS %>% map_df(~read.delim_plus(flnm = ., file_encode = FileEncodeCS, delimiter = DelimCS, header_rows = HeaderRowsCS)) %>%
  filter(Well != c("Content","Group")) %>%
  select(1, filename, everything()) %>%
  filter(Well != c("Content","Group")) %>%
  select(1, filename, everything()) %>%
  mutate(filename = str_replace(filename, pattern = paste(FP1, FP2, InstrumentPath,  sep = "/"), replacement = "")) %>%
  separate(col = filename, into = c("FP1", "Project", "DM", "ObsDate", "ObsTime", "plate", "csv"), sep = "([\\/\\_\\.\\:])", remove = FALSE) %>%
  select(-c("FP1", "csv")) %>%
  separate(col = plate, into = c("cplate", "plate"), sep = 5) %>%
  select(-c(cplate, Well)) %>%
  rename(Wavelength = X) %>%
  rename_all(funs(str_replace(., "0", ""))) %>%
  subset(Wavelength != "Wavelength [nm]" & Wavelength != "") %>%
  unite(datetime, ObsDate, ObsTime, remove = FALSE) %>%
  mutate(datetime = ymd_hm(datetime),
         ObsDate = ymd(ObsDate),
         Wavelength = as.numeric(as.character(Wavelength)),
         plate = as.numeric(as.character(plate))
  ) %>%
  pivot_longer(-c(filename:Wavelength), names_to = "well", values_to = "OD") %>% #long format better for downstream analyses; think about non-explicit column selection
  mutate(OD = as.numeric(as.character(OD))) %>%
  inner_join(MetaMediaBlank, by = c("plate" = "plate", "well" = "well", "Wavelength" = "Wavelength")) %>%
  mutate(CorrOD = OD - AvBlankOD) %>%
  filter(!is.na(OD)) %>%
  distinct() %>%
  group_by(id) %>% mutate(E_hours = as.numeric((datetime - datetime[1])/3600),
                                                  E_days = as.numeric((datetime - datetime[1])/86400)
                                                  ) %>% 
  ungroup()

FileIDOD <- "_OD_"
saveRDS(AbSpecCS, file.path(paste(FP1, DataOut, sep = "/"), 
paste(Project, FileIDOD, "GrowthLong.Rds", sep = ""), fsep = .Platform$file.sep))

```


```{r Impute Cellcount based on Cell/OD calibration, echo=FALSE}

GrowthLongCC <- full_join(AbSpecCS, CalibrationCellCount) %>%
  mutate(CorrOD = if_else(CorrOD < 0.001, 0.001, CorrOD)) %>% #experimentally test to set values below 0.001 to 0.001 (~detection limit device) 
  mutate(RegresCellCount_mL = CorrOD/estimate_slope) %>%
  full_join(CalibrationETR, by = c("id" = "CultureID", "ObsDate" = "ObsDate")) %>%
  mutate(ETR_JVPSII = par_ue*LRC_JVPSII_ETR_slope,
         JVPSII_cell = ETR_JVPSII/RegresCellCount_mL)

FileIDCC <- "_CC_"
saveRDS(GrowthLongCC, file.path(paste(FP1, DataOut, sep = "/"), 
paste(Project, FileIDCC, "GrowthLong.Rds", sep = ""), fsep = .Platform$file.sep))

```


```{r save GrowthLongChl, echo=FALSE}

GrowthLongChl <- AbSpecCS %>%
  mutate(Wavelength = as.character(Wavelength)) %>%
  filter(Wavelength %in% c("680", "720", "750")) %>%
  pivot_wider(id_cols = -c(OD, AvBlankOD), names_from = Wavelength, values_from = CorrOD, names_glue = "nm_{Wavelength}") %>%
  mutate("680min720" = nm_680 - nm_720, "680min750" = nm_680 - nm_750) %>%
  pivot_longer(cols = c(nm_680, nm_720, nm_750, "680min720", "680min750"), values_to = "CorrOD", names_to = "Wavelength") %>%
  mutate(Wavelength = str_remove(Wavelength, "nm_")) %>%
  mutate(CorrOD = if_else(CorrOD < 0.001, 0.001, CorrOD)) %>% #experimentally test to set values below 0.001 to 0.001 (~detection limit device) 
  full_join(CalibrationChloro) %>%
  mutate(RegresChl_ugL = CorrOD/estimate_Chl_ugL_mean) %>%
  full_join(CalibrationETR, by = c("id" = "CultureID", "ObsDate" = "ObsDate")) %>%
  mutate(ETR_JVPSII = par_ue*LRC_JVPSII_ETR_slope,
         JVPSII_chl = ETR_JVPSII/RegresChl_ugL)

FileIDChl <- "_Chl_"
saveRDS(GrowthLongChl, file.path(paste(FP1, DataOut, sep = "/"), 
paste(Project, FileIDChl, "GrowthLong.Rds", sep = ""), fsep = .Platform$file.sep))

```


