---
title: "Import media blank plate absorbance spectra for well plates"
author: "Maximilian Berthold"
date: "`r format(Sys.Date())`"
output:
  html_document:
    df_print: paged
    code_folding: hide   

---
Code taken from PGWAbSpectra.Rmd and modified to visualize data from blanks.

```{r set project variables, echo=FALSE}
Project <- "PGW"
Catalog <- "MURIS_catalog.csv"

#set variables for file import & processing of Absorbance files
FP1 <- ".."
FP2 <- "RawData"
InstrumentPath <- "CSdata"
BlankPath <- "blanks"
DataPath <- file.path(paste(FP1, FP2, InstrumentPath, BlankPath, sep = "/"), fsep = .Platform$file.sep)
FileIDSingle <- "_Ab_"
DataOut <- "ProcessData"

FileEncodeCS <- "UTF-8" 
DelimCS <- ","

#make this more robust to variable file formats by skipping rows until 'Well' detected; not yet implemented
#https://community.rstudio.com/t/read-csv-file-until/41711/2
HeaderRowsCS <- 6
```



```{r load libraries, echo=FALSE, message = FALSE, warning = FALSE} 
# libraries; Note check actual dependencies
library(tidyverse)
library(lubridate)
library(googledrive)
library(googlesheets4)
library(stringr)
library(broom)
library(knitr)
library(OneR)

```


```{r}

#deauthorizes access to googlesheet
gs4_deauth()

MetaData <- read_sheet("https://docs.google.com/spreadsheets/d/1QWMLB_0E9uNK0o67pypTZKjkyjEpBMEzoYTi1Db86Q8/edit?usp=sharing")

MediaData <- read_sheet("https://docs.google.com/spreadsheets/d/1E3C0_3ziDp-NnvvI5l7ZgqcanKZxSqgaWxk3uUmgRLA/edit?usp=sharing")

AbFilesBlank <- list.files(path = DataPath, pattern = FileIDSingle, full.names = TRUE) 
unique(duplicated(AbFilesBlank))

MediaData <- MediaData %>%
  select(MediaID, MeasuredSalinity_ppt) %>%
  rename("target_media_id" ="MediaID")
  
MetaData <- MetaData %>%
  mutate(ExpSalinity = (((culture_inocul_L * source_salinity)+(media_inocul_L*salinity))/(culture_inocul_L+media_inocul_L)))

#manually create spectral range of interest, change to actual spectral range by extracting from blanks measured
WL_grid <- expand_grid(
  Wavelength = seq(from=min(370), 
              to=max(750), 
              by = 10)
)
WL_Media_grid <- full_join(WL_grid, MediaData, by = character())

MetaMediaData <- full_join(MetaData, WL_Media_grid)

```


```{r data read adds filename and cdate, warning=FALSE, message=FALSE, echo=FALSE}

read.delim_plus <- function(flnm, file_encode, delimiter, header_rows){read.delim(flnm, fileEncoding = file_encode, sep = delimiter,  skip = header_rows, row.names = NULL) %>% mutate(filename = flnm)
}

impute_median <- function(x) replace(x, is.na(x), median(x, na.rm = TRUE))  #function to impute median average OD values of blanks at their respective wavelength for media, where blank measurements are missing
  

AbSpecBlanks <- AbFilesBlank %>% map_df(~read.delim_plus(flnm = ., file_encode = FileEncodeCS, delimiter = DelimCS, header_rows = HeaderRowsCS))  %>%
  filter(Well != c("Content","Group")) %>%
  select(1, filename, everything()) %>%
  mutate(filename = str_replace(filename, pattern = paste(FP1, FP2, InstrumentPath, BlankPath, sep = "/"), replacement = "")) %>%
  separate(col = filename, into = c("FP1", "Project", "DM", "date", "time", "plate","blank", "csv"), sep = "([\\/\\_\\.\\:])", remove = FALSE) %>%
  select(-c("FP1", "csv")) %>%
  separate(col = plate, into = c("cplate", "plate"), sep = 5) %>%
  select(-c(cplate, Well)) %>%
  rename(Wavelength = X) %>%
  rename_all(funs(str_replace(., "0", ""))) %>%
  subset(Wavelength != "Wavelength [nm]" & Wavelength != "") %>%
  unite(datetime, date, time, remove = TRUE) %>%
  mutate(datetime = ymd_hm(datetime),
         Wavelength = as.numeric(as.character(Wavelength)),
         plate = as.numeric(as.character(plate))
  ) %>%
  pivot_longer(cols = c(A1:D6), names_to = "well", values_to = "OD") %>% #long format better for downstream analyses
  mutate(OD = as.numeric(as.character(OD))) %>%
  rename("BlankOD" = "OD") %>%
  full_join(MetaMediaData) %>% #join with Meta and Media catalog 
  group_by(target_media_id, well, Wavelength, salinity) %>% #media with different salinity has different optical properties
  nest() %>%
  na.omit(well, Wavelength) %>%
  mutate(AvBlankOD = map(data, ~mean(.x$BlankOD, na.rm = TRUE))) %>% #impute median in case there are missing values
  unnest(cols = c(AvBlankOD)) %>%
  select(well, target_media_id, AvBlankOD, Wavelength, salinity)  %>%
  mutate_all(~ifelse(is.nan(.), NA, .)) %>%
  group_by(salinity, Wavelength) %>%
  mutate(AvBlankOD = impute_median(AvBlankOD))

saveRDS(AbSpecBlanks, file.path(paste(FP1, DataOut, sep = "/"),
        paste(Project, "MediaBlankAll.Rds", sep = "_"), fsep = .Platform$file.sep))

```

